export function convertGeoJSONToKML(geoJSON: any): string {
  let kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Ecoweeder Export</name>
    <description>Generated by Ecoweeder KML Generator</description>
    
    <Style id="polygonStyle">
      <LineStyle>
        <color>ff16a34a</color>
        <width>3</width>
      </LineStyle>
      <PolyStyle>
        <color>4d16a34a</color>
      </PolyStyle>
    </Style>
    
    <Style id="lineStyle">
      <LineStyle>
        <color>ff16a34a</color>
        <width>3</width>
      </LineStyle>
    </Style>
    
    <Style id="pointStyle">
      <IconStyle>
        <color>ff16a34a</color>
        <scale>1.0</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>
        </Icon>
      </IconStyle>
    </Style>
`;

  if (geoJSON.features && Array.isArray(geoJSON.features)) {
    geoJSON.features.forEach((feature: any, index: number) => {
      kml += convertFeatureToKML(feature, index);
    });
  }

  kml += `  </Document>
</kml>`;

  return kml;
}

function convertFeatureToKML(feature: any, index: number): string {
  const geometry = feature.geometry;
  const properties = feature.properties || {};
  const name = properties.name || `Feature ${index + 1}`;
  const description = properties.description || "";

  let kml = `    <Placemark>
      <name>${escapeXML(name)}</name>
      <description>${escapeXML(description)}</description>
`;

  switch (geometry.type) {
    case "Point":
      kml += `      <styleUrl>#pointStyle</styleUrl>
      <Point>
        <coordinates>${geometry.coordinates[0]},${geometry.coordinates[1]},0</coordinates>
      </Point>
`;
      break;

    case "LineString":
      kml += `      <styleUrl>#lineStyle</styleUrl>
      <LineString>
        <coordinates>
          ${geometry.coordinates
            .map((coord: number[]) => `${coord[0]},${coord[1]},0`)
            .join("\n          ")}
        </coordinates>
      </LineString>
`;
      break;

    case "Polygon":
      kml += `      <styleUrl>#polygonStyle</styleUrl>
      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>
              ${geometry.coordinates[0]
                .map((coord: number[]) => `${coord[0]},${coord[1]},0`)
                .join("\n              ")}
            </coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
`;
      break;

    case "MultiPoint":
      geometry.coordinates.forEach((coord: number[]) => {
        kml += `      <Point>
        <coordinates>${coord[0]},${coord[1]},0</coordinates>
      </Point>
`;
      });
      break;

    case "MultiLineString":
      geometry.coordinates.forEach((line: number[][]) => {
        kml += `      <LineString>
        <coordinates>
          ${line
            .map((coord: number[]) => `${coord[0]},${coord[1]},0`)
            .join("\n          ")}
        </coordinates>
      </LineString>
`;
      });
      break;

    case "MultiPolygon":
      geometry.coordinates.forEach((polygon: number[][][]) => {
        kml += `      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>
              ${polygon[0]
                .map((coord: number[]) => `${coord[0]},${coord[1]},0`)
                .join("\n              ")}
            </coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
`;
      });
      break;
  }

  kml += `    </Placemark>
`;
  return kml;
}

function escapeXML(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
